name: build
on:
  push:
  workflow_dispatch:

jobs:
  build-on-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        mode:
          - { full: Debug,          short: debug }
          - { full: RelWithDebInfo, short: fat   }
          - { full: MinSizeRel,     short: slim  }

    name: ${{ matrix.mode.short }} (Ubuntu x86_64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build
        run: |
          mkdir -p /tmp/build
          cd /tmp/build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode.full }} ${{ github.workspace }}
          cmake --build . --verbose --parallel

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: upd-elf-x86_64-${{ matrix.mode.short }}
          path: |
            /tmp/build/upd
            /tmp/build/drivers/**/dst/
          if-no-files-found: ignore

  build-on-win64:
    strategy:
      fail-fast: false
      matrix:
        mode:
          - { full: RelWithDebInfo, short: fat   }
          - { full: MinSizeRel,     short: slim  }

    name: ${{ matrix.mode.short }} (Win64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: ilammy/msvc-dev-cmd@v1

      - name: building
        run: |
          mkdir -p /tmp/build
          cd /tmp/build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.mode.full }} ${{ github.workspace }}
          cmake --build . --verbose --parallel

      - name: 'uploading artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: upd-coff-x86_64-${{ matrix.mode.short }}
          path: |
            /tmp/build/upd.exe
            /tmp/build/drivers/**/dst/
          if-no-files-found: ignore

